name: Auto Commit

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Random sleep (0â€“3600 detik)
        run: sleep $((RANDOM % 3600))

      - name: Set git identity
        run: |
          git config --global user.name "vryptt-bot"
          git config --global user.email "vryptt@vrypt.com"

      - name: Update file
        run: |
          echo "Update: $(date)" >> auto.md

      - name: Commit changes
        run: |
          git add auto.md
          git commit -m "auto: update $(date)" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin HEAD
